export const PERMISSIONS = [
  { key: "dashboard.view", label: "Lihat dasbor", group: "Dasbor" },
  { key: "dashboard.filterDate", label: "Filter Tanggal", group: "Dasbor" },
  { key: "dashboard.viewTransactions", label: "Lihat Total Transaksi", group: "Dasbor" },
  { key: "dashboard.viewTurnover", label: "Lihat Omset", group: "Dasbor" },
  { key: "dashboard.viewBankFee", label: "Lihat Potongan Bank", group: "Dasbor" },
  { key: "dashboard.viewProfit", label: "Lihat Profit", group: "Dasbor" },
  { key: "dashboard.viewChart", label: "Lihat Detail Chart", group: "Dasbor" },
  { key: "dashboard.annualReport", label: "Laporan Tahunan", group: "Dasbor" },
  { key: "dashboard.monthlyReport", label: "Laporan Bulanan", group: "Dasbor" },
  { key: "inventory.view", label: "Lihat inventori", group: "Inventori" },
  { key: "inventory.manage", label: "Tambah Barang", group: "Inventori" },
  { key: "inventory.edit", label: "Edit Barang", group: "Inventori" },
  { key: "inventory.delete", label: "Hapus Barang", group: "Inventori" },
  { key: "categories.view", label: "Lihat kategori", group: "Kategori" },
  { key: "categories.manage", label: "Tambah kategori", group: "Kategori" },
  { key: "categories.edit", label: "Edit kategori", group: "Kategori" },
  { key: "categories.delete", label: "Hapus kategori", group: "Kategori" },
  { key: "suppliers.view", label: "Lihat supplier", group: "Supplier" },
  { key: "suppliers.manage", label: "Tambah supplier", group: "Supplier" },
  { key: "suppliers.edit", label: "Edit supplier", group: "Supplier" },
  { key: "suppliers.delete", label: "Hapus supplier", group: "Supplier" },
  { key: "customers.view", label: "Lihat pelanggan", group: "Pelanggan" },
  { key: "customers.manage", label: "Tambah pelanggan", group: "Pelanggan" },
  { key: "customers.edit", label: "Edit pelanggan", group: "Pelanggan" },
  { key: "customers.delete", label: "Hapus pelanggan", group: "Pelanggan" },
  { key: "transactions.view", label: "Lihat transaksi", group: "Transaksi" },
  { key: "transactions.manage", label: "Tambah transaksi", group: "Transaksi" },
  { key: "transactions.viewAsset", label: "Lihat Total Aset", group: "Transaksi" },
  { key: "transactions.viewProfit", label: "Lihat Profit", group: "Transaksi" },
  { key: "transactions.delete", label: "Hapus Transaksi", group: "Transaksi" },
  { key: "transactions.edit", label: "Edit Transaksi", group: "Transaksi" },
  { key: "transactions.exportExcel", label: "Laporan Excel Transaksi", group: "Transaksi" },
  { key: "transactions.profitWA", label: "Total Profit Laporan WA", group: "Transaksi" },
  { key: "bankTransfers.view", label: "Lihat MiniATM", group: "MiniATM" },
  { key: "bankTransfers.manage", label: "Tambah transaksi MiniATM", group: "MiniATM" },
  { key: "bankTransfers.edit", label: "Edit transaksi MiniATM", group: "MiniATM" },
  { key: "bankTransfers.delete", label: "Hapus transaksi MiniATM", group: "MiniATM" },
  { key: "funds.view", label: "Lihat sumber dana", group: "Sumber Dana" },
  { key: "funds.manage", label: "Tambah sumber dana", group: "Sumber Dana" },
  { key: "funds.edit", label: "Edit sumber dana", group: "Sumber Dana" },
  { key: "fundMutations.view", label: "Lihat mutasi saldo", group: "Mutasi Saldo" },
  { key: "fundMutations.manage", label: "Kelola mutasi saldo", group: "Mutasi Saldo" },
  { key: "fundMutations.moveCreate", label: "Tambah", group: "Pindah Saldo" },
  { key: "fundMutations.deposit", label: "Tambah Saldo", group: "Ambil Saldo & Tambah Saldo" },
  { key: "fundMutations.withdraw", label: "Ambil Saldo Tambah", group: "Ambil Saldo & Tambah Saldo" },
  { key: "services.view", label: "Lihat service", group: "Service" },
  { key: "services.manage", label: "Tambah service", group: "Service" },
  { key: "services.edit", label: "Edit Service", group: "Service" },
  { key: "services.delete", label: "Hapus Service", group: "Service" },
  { key: "finance.view", label: "Lihat keuangan", group: "Keuangan" },
  { key: "finance.manage", label: "Tambah pengeluaran", group: "Keuangan" },
  { key: "finance.edit", label: "Edit keuangan", group: "Keuangan" },
  { key: "finance.delete", label: "Hapus keuangan", group: "Keuangan" },
  { key: "reports.view", label: "Lihat laporan", group: "Laporan" },
  { key: "reports.export", label: "Export laporan", group: "Laporan" },
  { key: "receivables.view", label: "Lihat utang piutang", group: "Utang Piutang" },
  { key: "receivables.manage", label: "Tambah utang piutang", group: "Utang Piutang" },
  { key: "receivables.edit", label: "Edit utang piutang", group: "Utang Piutang" },
  { key: "receivables.delete", label: "Hapus utang piutang", group: "Utang Piutang" },
  { key: "receipts.view", label: "Lihat dan cetak struk", group: "Cetak Struk" },
  { key: "receipts.manage", label: "Kelola master dan pengaturan struk", group: "Cetak Struk" },
  { key: "payroll.view", label: "Lihat penggajian", group: "Penggajian" },
  { key: "payroll.manage", label: "Tambah penggajian", group: "Penggajian" },
  { key: "payroll.edit", label: "Edit penggajian", group: "Penggajian" },
  { key: "payroll.delete", label: "Hapus penggajian", group: "Penggajian" },
  { key: "settings.view", label: "Lihat pengaturan", group: "Pengaturan" },
  { key: "settings.backup", label: "Unduh backup", group: "Pengaturan" },
  { key: "settings.adminFee", label: "Kelola admin otomatis", group: "Pengaturan" }
] as const;

export type PermissionKey = typeof PERMISSIONS[number]["key"];
export const PERMISSION_DEPENDENCIES: Partial<Record<PermissionKey, PermissionKey>> = {
  "inventory.manage": "inventory.view",
  "inventory.edit": "inventory.manage",
  "inventory.delete": "inventory.manage",
  "categories.manage": "categories.view",
  "categories.edit": "categories.manage",
  "categories.delete": "categories.manage",
  "suppliers.manage": "suppliers.view",
  "suppliers.edit": "suppliers.manage",
  "suppliers.delete": "suppliers.manage",
  "customers.manage": "customers.view",
  "customers.edit": "customers.manage",
  "customers.delete": "customers.manage",
  "transactions.manage": "transactions.view",
  "transactions.viewAsset": "transactions.view",
  "transactions.viewProfit": "transactions.view",
  "transactions.delete": "transactions.manage",
  "transactions.edit": "transactions.manage",
  "transactions.exportExcel": "transactions.view",
  "transactions.profitWA": "transactions.view",
  "bankTransfers.manage": "bankTransfers.view",
  "bankTransfers.edit": "bankTransfers.manage",
  "bankTransfers.delete": "bankTransfers.manage",
  "funds.manage": "funds.view",
  "funds.edit": "funds.manage",
  "fundMutations.manage": "fundMutations.view",
  "fundMutations.moveCreate": "fundMutations.manage",
  "fundMutations.deposit": "fundMutations.manage",
  "fundMutations.withdraw": "fundMutations.manage",
  "services.manage": "services.view",
  "services.edit": "services.manage",
  "services.delete": "services.manage",
  "finance.manage": "finance.view",
  "finance.edit": "finance.manage",
  "finance.delete": "finance.manage",
  "reports.export": "reports.view",
  "receivables.manage": "receivables.view",
  "receivables.edit": "receivables.manage",
  "receivables.delete": "receivables.manage",
  "receipts.manage": "receipts.view",
  "payroll.manage": "payroll.view",
  "payroll.edit": "payroll.manage",
  "payroll.delete": "payroll.manage",
  "settings.backup": "settings.view",
  "settings.adminFee": "settings.view"
};

export const DEFAULT_STAFF_PERMISSIONS: PermissionKey[] = [
  "dashboard.view",
  "dashboard.filterDate",
  "dashboard.viewTransactions",
  "dashboard.viewTurnover",
  "dashboard.viewChart",
  "customers.view",
  "customers.manage",
  "customers.edit",
  "transactions.view",
  "transactions.manage",
  "bankTransfers.view",
  "bankTransfers.manage",
  "bankTransfers.edit",
  "services.view",
  "services.manage",
  "services.edit",
  "services.delete",
  "settings.view",
  "settings.backup"
];

export function hasPermission(role: "admin" | "staff", permissions: string[], key: PermissionKey) {
  if (role === "admin" || key === "dashboard.view") return true;
  return permissions.includes(key);
}
