export const PERMISSIONS = [
  { key: "dashboard.view", label: "Lihat dasbor", group: "Dasbor" },
  { key: "dashboard.filterDate", label: "Filter Tanggal", group: "Dasbor" },
  { key: "dashboard.viewTransactions", label: "Lihat Total Transaksi", group: "Dasbor" },
  { key: "dashboard.viewTurnover", label: "Lihat Omset", group: "Dasbor" },
  { key: "dashboard.viewBankFee", label: "Lihat Potongan Bank", group: "Dasbor" },
  { key: "dashboard.viewProfit", label: "Lihat Profit", group: "Dasbor" },
  { key: "dashboard.viewChart", label: "Lihat Detail Chart", group: "Dasbor" },
  { key: "dashboard.annualReport", label: "Laporan Tahunan", group: "Dasbor" },
  { key: "dashboard.monthlyReport", label: "Laporan Bulanan", group: "Dasbor" },
  { key: "inventory.view", label: "Lihat inventori", group: "Inventori" },
  { key: "inventory.manage", label: "Kelola inventori", group: "Inventori" },
  { key: "categories.view", label: "Lihat kategori", group: "Kategori" },
  { key: "categories.manage", label: "Kelola kategori", group: "Kategori" },
  { key: "suppliers.view", label: "Lihat supplier", group: "Supplier" },
  { key: "suppliers.manage", label: "Kelola supplier", group: "Supplier" },
  { key: "customers.view", label: "Lihat pelanggan", group: "Pelanggan" },
  { key: "customers.manage", label: "Kelola pelanggan", group: "Pelanggan" },
  { key: "transactions.view", label: "Lihat transaksi", group: "Transaksi" },
  { key: "transactions.manage", label: "Kelola transaksi", group: "Transaksi" },
  { key: "transactions.viewAsset", label: "Lihat Total Aset", group: "Transaksi" },
  { key: "transactions.viewProfit", label: "Lihat Profit", group: "Transaksi" },
  { key: "transactions.delete", label: "Hapus Transaksi", group: "Transaksi" },
  { key: "transactions.edit", label: "Edit Transaksi", group: "Transaksi" },
  { key: "transactions.exportExcel", label: "Laporan Excel Transaksi", group: "Transaksi" },
  { key: "transactions.profitWA", label: "Total Profit Laporan WA", group: "Transaksi" },
  { key: "bankTransfers.view", label: "Lihat MiniATM", group: "MiniATM" },
  { key: "bankTransfers.manage", label: "Kelola MiniATM", group: "MiniATM" },
  { key: "funds.view", label: "Lihat sumber dana", group: "Sumber Dana" },
  { key: "funds.manage", label: "Kelola sumber dana", group: "Sumber Dana" },
  { key: "fundMutations.view", label: "Lihat mutasi saldo", group: "Mutasi Saldo" },
  { key: "fundMutations.manage", label: "Kelola mutasi saldo", group: "Mutasi Saldo" },
  { key: "fundMutations.moveDelete", label: "Hapus", group: "Pindah Saldo" },
  { key: "fundMutations.moveCreate", label: "Tambah", group: "Pindah Saldo" },
  { key: "fundMutations.deposit", label: "Tambah Saldo", group: "Ambil Saldo & Tambah Saldo" },
  { key: "fundMutations.withdraw", label: "Ambil Saldo Tambah", group: "Ambil Saldo & Tambah Saldo" },
  { key: "fundMutations.withdrawDelete", label: "Ambil Saldo Hapus", group: "Ambil Saldo & Tambah Saldo" },
  { key: "services.view", label: "Lihat service", group: "Service" },
  { key: "services.manage", label: "Kelola service", group: "Service" },
  { key: "finance.view", label: "Lihat keuangan", group: "Keuangan" },
  { key: "finance.manage", label: "Kelola keuangan", group: "Keuangan" },
  { key: "reports.view", label: "Lihat laporan", group: "Laporan" },
  { key: "reports.export", label: "Export laporan", group: "Laporan" },
  { key: "receivables.view", label: "Lihat utang piutang", group: "Utang Piutang" },
  { key: "receivables.manage", label: "Kelola utang piutang", group: "Utang Piutang" },
  { key: "receipts.view", label: "Lihat dan cetak struk", group: "Cetak Struk" },
  { key: "receipts.manage", label: "Kelola master dan pengaturan struk", group: "Cetak Struk" },
  { key: "payroll.view", label: "Lihat penggajian", group: "Penggajian" },
  { key: "payroll.manage", label: "Kelola penggajian", group: "Penggajian" },
  { key: "settings.view", label: "Lihat pengaturan", group: "Pengaturan" },
  { key: "settings.backup", label: "Unduh backup", group: "Pengaturan" }
] as const;

export type PermissionKey = typeof PERMISSIONS[number]["key"];
export const PERMISSION_DEPENDENCIES: Partial<Record<PermissionKey, PermissionKey>> = {
  "inventory.manage": "inventory.view",
  "categories.manage": "categories.view",
  "suppliers.manage": "suppliers.view",
  "customers.manage": "customers.view",
  "transactions.manage": "transactions.view",
  "transactions.viewAsset": "transactions.view",
  "transactions.viewProfit": "transactions.view",
  "transactions.delete": "transactions.manage",
  "transactions.edit": "transactions.manage",
  "transactions.exportExcel": "transactions.view",
  "transactions.profitWA": "transactions.view",
  "bankTransfers.manage": "bankTransfers.view",
  "funds.manage": "funds.view",
  "fundMutations.manage": "fundMutations.view",
  "fundMutations.moveDelete": "fundMutations.view",
  "fundMutations.moveCreate": "fundMutations.manage",
  "fundMutations.deposit": "fundMutations.manage",
  "fundMutations.withdraw": "fundMutations.manage",
  "fundMutations.withdrawDelete": "fundMutations.manage",
  "services.manage": "services.view",
  "finance.manage": "finance.view",
  "reports.export": "reports.view",
  "receivables.manage": "receivables.view",
  "receipts.manage": "receipts.view",
  "payroll.manage": "payroll.view",
  "settings.backup": "settings.view"
};

export const DEFAULT_STAFF_PERMISSIONS: PermissionKey[] = [
  "dashboard.view",
  "customers.view",
  "customers.manage",
  "transactions.view",
  "transactions.manage",
  "bankTransfers.view",
  "bankTransfers.manage",
  "services.view",
  "services.manage",
  "settings.view",
  "settings.backup"
];

export function hasPermission(role: "admin" | "staff", permissions: string[], key: PermissionKey) {
  return role === "admin" || key === "dashboard.view" || permissions.includes(key);
}
